theme: jekyll-theme-minimal
title: Welcome to Bill's homepage!
email: billsizhao.wu@gmail.com
description: "[LinkedIn](https://www.linkedin.com/in/sizhao-bill-wu/)  \n[Instagram]("https://www.instagram.com/billl.wu/")"
