theme: jekyll-theme-minimal
title: Welcome to Bill's homepage!
description: My framework outperforms the <a href="https://www.linkedin.com/in/sizhao-bill-wu/">current industry standard</a> as can be seen in publicly available <a href="https://www.instagram.com/billl.wu/">benchmarks</a>
